// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQm2dvgSIRyhqrdRv9vi3cnfyVULSDKO0',
    appId: '1:1017997992708:web:c4383c1ee763abd7742651',
    messagingSenderId: '1017997992708',
    projectId: 'speech-emotion-2297a',
    authDomain: 'speech-emotion-2297a.firebaseapp.com',
    storageBucket: 'speech-emotion-2297a.appspot.com',
    measurementId: 'G-THZ247271C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQn1Nbl8USQp7eWB0G1zuz1nO3lCqvGE',
    appId: '1:1017997992708:android:8c3131e7b34ab409742651',
    messagingSenderId: '1017997992708',
    projectId: 'speech-emotion-2297a',
    storageBucket: 'speech-emotion-2297a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VGMOTn_toKKUFpLdF_gachFYpOqi5Nw',
    appId: '1:1017997992708:ios:d6c8ad2a607dc4ed742651',
    messagingSenderId: '1017997992708',
    projectId: 'speech-emotion-2297a',
    storageBucket: 'speech-emotion-2297a.appspot.com',
    iosBundleId: 'com.example.gpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VGMOTn_toKKUFpLdF_gachFYpOqi5Nw',
    appId: '1:1017997992708:ios:d6c8ad2a607dc4ed742651',
    messagingSenderId: '1017997992708',
    projectId: 'speech-emotion-2297a',
    storageBucket: 'speech-emotion-2297a.appspot.com',
    iosBundleId: 'com.example.gpProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQm2dvgSIRyhqrdRv9vi3cnfyVULSDKO0',
    appId: '1:1017997992708:web:ac17fb4c3fee9d44742651',
    messagingSenderId: '1017997992708',
    projectId: 'speech-emotion-2297a',
    authDomain: 'speech-emotion-2297a.firebaseapp.com',
    storageBucket: 'speech-emotion-2297a.appspot.com',
    measurementId: 'G-X0XLW6MK68',
  );
}
